---
# List of options for a Jupyter Widget dropdown menu
# Consists of a label and a Wikidata property P number
# For each P number, you should have a csv file of that name for pre-loaded content
# Example: kg-P195.csv 

general:
- csv_template: 'kg-{}.csv'
- num_panels: 3

dropdown:
- '-'
- instance of (P31)
- collection/institution (P195)
- artist/creator (P170)
- genre (P136)
- depiction (P180)
# - movement (P135)
# - made from material (P186)
# - fabrication method (P2079)